create extension if not exists pgcrypto;

create table if not exists public.expedientes (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  status text not null default 'recibido',
  full_name text not null,
  profession text not null,
  email text not null,
  phone text not null,
  address_source text not null check (address_source in ('ine','proof','other')),
  street text not null,
  neighborhood text not null,
  postal_code text not null,
  city text not null,
  state text not null,
  consent boolean not null default false,
  pdf_path text,
  email_sent_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.expediente_beneficiarios (
  id bigint generated by default as identity primary key,
  expediente_id uuid not null references public.expedientes(id) on delete cascade,
  full_name text not null,
  relationship text not null,
  percentage numeric(5,2) not null check (percentage > 0 and percentage <= 100)
);

create table if not exists public.expediente_documentos (
  id bigint generated by default as identity primary key,
  expediente_id uuid not null references public.expedientes(id) on delete cascade,
  kind text not null check (kind in ('ine_front','ine_back','address_proof','compiled_pdf')),
  storage_path text not null,
  original_name text,
  mime_type text,
  created_at timestamptz not null default now()
);

alter table public.expedientes enable row level security;
alter table public.expediente_beneficiarios enable row level security;
alter table public.expediente_documentos enable row level security;

-- No anon/authenticated policies are intentionally created.
-- Only server-side service-role access is allowed for sensitive client data.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'expedientes-privados',
  'expedientes-privados',
  false,
  10485760,
  array['image/jpeg','image/png','application/pdf']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- The bucket remains private and has no public storage policies.
